### PR TITLE
Fix currentTime function when offset is not used

### PR DESCRIPTION
**Pull request by DanielWare**
Bug fix for [#39](https://github.com/cladera/videojs-offset/issues/39)

## Description
In cases where videojs-offset is loaded but no used, we should fall back to videojs implementation of currentTime. specifically we check to see if _offsetStart is defined before using videojs-offset logic.

## Specific Changes proposed
There are 2 code paths for currentTime. In both cases (seconds argument is defined/undefined) we check if this._offsetStart is defined, and if not, we call the super class version of the function.

### CODE REVIEW

**Comment by DanielWare** [comment]
I also updated the implementation of duration. It may have been where this error began.

**Comment by DanielWare** [comment]
@cladera Sorry, I'm a bit new to this whole pull request thing. What does that mean?

**Comment by cladera** [comment]
Hi @DanielWare I just published a new version which upgrades the videojs-plugin generator because the CI was not passing in any PR. 

You need to rebase your branch onto master and then push your branch again.

**Comment by DanielWare** [comment]
@cladera Thanks! I think I have merged your changes and hopefully should be good now.

**Comment by DanielWare** [comment]
@cladera looks like we need to add [shx](https://github.com/shelljs/shx) to the dev dependencies to fix the build.

**Comment by cladera** [comment]
@DanielWare No, the build was ok. The problem is your branch did not pass the lint check:

```
   99:1  error  Expected indentation of 12 spaces but found 10  indent
  106:1  error  Expected indentation of 10 spaces but found 8   indent
```

**Pull request closed without merging**
